### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [HelpMeNowThanks/Country-Guessing-Game#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Jautiena** [comment]
Done? I dunno how licenses work so i just made a license file and pasted it, hope that fixed it :)

**Comment by TechnologyClassroom** [comment]
Great choice!
